[package]
name = "arp_spoofing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.4.1"
pnet = "0.34.0"
serde_json = "1.0.107"
time = "0.3.30"
